### ISSUE TITLE
Move Bonds out of ACE.jl

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACE.jl#121]
@zhanglw0521 @MatthiasSachs How do you feel about moving bonds out of `ACE.jl` into a new repo `ACEbonds.jl`. That way I can keep moving `ACE.jl` along without maintaining compatibility with the bonds implementation.

**Comment by zhanglw0521** [comment]
I am ok with that. Just one thing to clarify - will the cylindrical/ellipsoidal cutoff also be moved to `ACEbonds.jl` or do they still lie in `ACE.jl`?

**Comment by cortner** [comment]
I want to move anything related to bonds into ACEbonds.jl. ACE.jl is getting too complex for me to keep it all in my head.

**Comment by zhanglw0521** [comment]
That was how I understood the proposal too. I just think that those two cutoffs can go with `ACEbonds.jl` as I can hardly come up with other applications of these kinds of cutoff. If there is any, it must be really similar to bonds and we can then consider renaming `ACEbonds.jl` to something else.

**Comment by cortner** [comment]
ok we want the same thing and I agree with you that this is the main / maybe only application.

**Comment by cortner** [comment]
I would actually consider moving Bonds back into ACE.jl but only much later once it has fully stabilized and we are starting to enforce backward compatibility.

**Comment by MatthiasSachs** [comment]
Yes, I don't mind at all! Who is going to set up the `ACEbonds.jl` repository?

**Comment by cortner** [comment]
I will set it up, but I won't mind at all if the two of you want to coordinate to get a first version to work.

**Comment by cortner** [comment]
There is NO RUSH whatsoever for this I think.

**Comment by cortner** [comment]
Thank you for agreeing. I'll go ahead and remove all bonds code after the current PR I'm working on.

**Comment by cortner** [comment]
done - cf #126 

The last version of ACE.jl that comes with bonds included is `version = "0.12.33"` - please make this an upper bound in your projects. Once the new ACEbonds is ready you can then move over your projects to that package.

**Comment by cortner** [comment]
0.12.34 is now tagged as the first version without the bonds code. So ACEbonds.jl needs to use 0.12.34 as a lower bound for ACE.jl
