### ISSUE TITLE
PolyPairPots scaling function

### ISSUE THREAD

**Issue by casv2** [ACEsuit/ACE.jl#16]
In order to add a `scaling(::PolyPairPots)` function, we need to get a second derivative estimate of the `OrthPolyBasis` initially. Would I need to write a `evaluate_2d!(.. J::OrthPolyBasis, ...)` function and calculate the second derivatives over the transformed `t` (given `[r_in,r_cut]` and a transform)? Or is there a more simple estimate for the laplacian like for the `RPIBasis`?

**Comment by cortner** [comment]
We only use very rough estimates anyhow. If this is urgent for you, please leave it with me and I'll put something together. Most likely today, but over the weekend of not. (ping me if you haven't hear by Monday)

**Comment by cortner** [comment]
I've added the scaling for pair potentials in `v0.8.3`. I did some minimal tests, let me know if there are problems.
