### ISSUE TITLE
Changing maxdeg results in unexpected force behaviour

### ISSUE THREAD

**Issue by davkovacs** [ACEsuit/ACE.jl#19]
When the maxdeg parameter is changed from 1.0 even a bit (to 0.95) to decrease the overall size of the basis set, it causes large errors in the forces (but not in the energies).

**Comment by cortner** [comment]
CF script and data at 
```
https://github.com/cortner/acebug_david_maxdeg
```
to test this. Running with `maxdeg = 0.95` causes extremely strange results.

**Comment by cortner** [comment]
@davkovacs did we ever sort this out? I have a vague memory we explained what happened and decided what to do about it, but I'm not sure this constitutes closing the issue?

**Comment by davkovacs** [comment]
I don't remember explaining it. I think we just settled with not changing `maxdeg` from 1.0

**Comment by cortner** [comment]
I see - maybe I'll leave it open and we can revisit after the 2.0 rewrite.

**Comment by casv2** [comment]
I think this still is a bug, it's giving me issues too

**Comment by cortner** [comment]
Can you say more please?

**Comment by casv2** [comment]
Essentially it seems that when you set up a basis using /examples/new_degree.jl what happens is that your adjusted basis (controlled by `maxdeg`) ends up having good energy/forces training errors, but very weird force test errors. I'm not sure why, the energies seem fine in the test. It's not regularisation I think because the forces can be 1E6 off easily. So I guess the derivatives when adjusting the `maxdeg` in the `rpi_basis` leads to weird derivatives in the basis?

**Comment by cortner** [comment]
I don’t understand what this could have to do with training / test errors... it just chooses a basis

**Comment by casv2** [comment]
Let me try to put together a MWE

**Comment by casv2** [comment]
My bad it has weird force errors for both test/train, I've put together a MWE in `the-knowledge/ACE/ACE_basis_bug` including my .tomls

**Comment by cortner** [comment]
In ACE2 I've now introduced a new `BasisSelector` interface, where all these problems should just go away. There is now a single object, e.g., `SparseBasis` which takes a basis function as input, e.g., 
```julia 
bb = [ (n = 2, l = 3, m = -1), (n = 3, l = 2, m = 1), ... ]
```
and determines things like `degree`, whether it is part of the basis (`isadmissible`) etc. Even the correlation-order is part of this interface now and no longer a separate property.
