### ISSUE TITLE
Pyjulip problems

### ISSUE THREAD

**Issue by davkovacs** [ACEsuit/ACE.jl#43]
We have had problems setting up the stable ACE1 with Pyjulip. One of the problems was with Python version (need to have Python 3.8 or older, not 3.9.) The other problem is potentially with JuLIP v0.12, need 0.11. But this latter one is to be confirmed.

**Comment by cortner** [comment]
shall we close this since we now have [ACEinterfaces](https://github.com/ACEsuit/ACEinterfaces)

**Comment by cortner** [comment]
@davkovacs shall we close this since we now have ACEinterfaces?
