### ISSUE TITLE
Degree and Basis Selector

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACE.jl#65]
We need to revise the interface for basis selectors. At the moment it is acting as if the "degree" is not needed, but this is not true. The one-particle basis must be sorted by degree, and the "isadmissable" function must be monotone. This all suggests that we should maybe revert to the "degree" implementation and drop the "isadmissible" version altogether.

**Comment by cortner** [comment]
moving on now to implement the `level`

**Comment by MatthiasSachs** [comment]
Great! Should I add/do anything?

**Comment by cortner** [comment]
need to be careful when we remove the upper bounds on the one-particle basis to make sure nothing goes wrong.

**Comment by cortner** [comment]
> Great! Should I add/do anything?

not yet, I'd like to think this through a bit.

**Comment by cortner** [comment]
ok, level is done and will be finished in the PR today hopefully. I'm moving the discussion now to a separate issue on redesigning the basis selection interface altogether.
