### ISSUE TITLE
Element-pair dependant radial transform (r0)

### ISSUE THREAD

**Issue by LarsSchaaf** [ACEsuit/ACE.jl#77]
I would like to be able to adapt the radial basis depending on both atomic species of the atoms involved. More specifically, I would like to be able to set the radial transform (r0) based on the pair of involved elements.

Why does this make sense? Why is this important?

- **General:** In a given training set the covalent bond radii can vary significantly. Meaning that the distance of interest varies drastically based on the elements invovled. At the most extreem case, the C-H distance is much smaller than a typical C-large atom distance.
- **Specific Case (Metal organic frameworks)**: particularly bad, in this training set, the smallest C-H distance is 0.98A , while the smallest C-Mg distane is 3A.

**Comment by cortner** [comment]
We've often talked about this, and in fact even considered providing a learnable transform. Do you need this for v0.8 or for the development branch?

**Comment by casv2** [comment]
v0.8

**Comment by cortner** [comment]
ok, so the functionality you need is that instead of 
```julia
Rn( x(rij) ) 
```
you want 
```julia
Rn( x(rij, zi, zj) )
```
correct?

**Comment by cortner** [comment]
v0.8 makes this a more difficult proposition, but I will try

**Comment by casv2** [comment]
Yes that's exactly what he needs!

**Comment by cortner** [comment]
ok, and maybe prototype implementations along the lines of 
```
  x(rij, zi, zj) =  (1 + r0[zi, zj]) / (1 + r)^p[zi, zj]
```

**Comment by cortner** [comment]
There is just one caveat with all this, in v0.8, I can't easily create multiple Rn bases for each (zi, zj) component so I'll need to guarantee that all (zi, zj) pairs give transforms that map to the same domain. (I'm mostly recording this for myself, no need to engage with it ...)

**Comment by cortner** [comment]
cf PR #79

**Comment by LarsSchaaf** [comment]
Note, If I set the inner cutoff to anything other than 0.0, I get errors with the transform being out of range. 

```
ERROR: LoadError: AssertionError: transform(::MultiTransfrom, r) is only defined for r = rin, rcut
Stacktrace:
 [1] transform(t::ACE.Transforms.MultiTransform{3, ACE.Transforms.AffineT{Float64, PolyTransform{Int64, Float64}}}, r::Float64)
   @ ACE.Transforms ~/.julia/dev/ACE/src/polynomials/transforms.jl:263
 [2] transformed_jacobi(maxdeg::Int64, trans::ACE.Transforms.MultiTransform{3, ACE.Transforms.AffineT{Float64, PolyTransform{Int64, Float64}}}, rcut::Float64, rin::Float64; kwargs::Base.Iterators.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:pcut,), Tuple{Int64}}})
   @ ACE.OrthPolys ~/.julia/dev/ACE/src/polynomials/orthpolys.jl:324
 [3] top-level scope
   @ ~/.julia/dev/ACE/test/polynomials/test_multitrans.jl:87
in expression starting at /home/lls34/.julia/dev/ACE/test/polynomials/test_multitrans.jl:87
```

**Comment by LarsSchaaf** [comment]
I was wondering about the possibility of having **atom specific cutoffs**. If I understand it correctly, our basis needs to be orthogonal after we have transformed the radial basis to our new domain [-1,1]. Setting atom specific cutoffs or also transforms, would then mean that the basis isn’t orthogonal in the untransformed space, but is that a problem? No right? So, as long as we are always mapping between [-1,1], having different cutoffs for different species shouldn’t be a problem?

The inner cutoff could then be set to a percentage (~90%) of the sum of **covalent bond radii** for a specific atom pair. For a system involving HH and MgMg, this can range from 0.56A to 2.58A. A variable inner cutoff would also mean that the current functional form (PolyTransform) of the radial transform would be more applicable. Currently with just altering r0, the derivative of the transform is still a maximum at the inner cutoff and a lot of the domain will never be explored for large covalent bond radii.

**Comment by cortner** [comment]
ok - so the proposal is to allow individual cutoffs for each (zi, zj) pair, then always map the `[rin, rout]` domain to `[-1, 1]` where the orthogonality is then enforced. This makes perfect sense to me but I'm a bit cautious about how easy it will be. I will need to take a careful look at the code.

**Comment by gabor1** [comment]
Exactly

**Comment by gabor1** [comment]
I realised, as I was trying to explain it to Lars, that I never understood when you said before that inner cutoffs can’t be element dependent.

**Comment by cortner** [comment]
... hm, looks doable ... maybe even today.

**Comment by cortner** [comment]
Would this be ok: 
```Julia
transforms = Dict(
     (:Fe, :C) => PolyTransform(2, (rnn(:Fe)+rnn(:C)) / 2), 
     (:C, :Al) => PolyTransform(2, (rnn(:Al)+rnn(:C)) / 2), 
     (:Fe, :Al) => PolyTransform(2, (rnn(:Al)+rnn(:Fe)) / 2), 
     (:Fe, :Fe) => PolyTransform(2, rnn(:Fe)), 
     (:Al, :Al) => PolyTransform(2, rnn(:Al)), 
     (:C, :C) => PolyTransform(2, rnn(:C)), 
     (:Al, :Fe) => PolyTransform(2, (rnn(:Al)+rnn(:Fe)) / 2 + 1)  
   )

cutoffs = Dict(
   (:Fe, :C) => (1.5, 5.0), 
   (:C, :Al) => (0.7, 6.0), 
   (:Fe, :Al) => (2.2, 4.5), 
   (:Fe, :Fe) => (2.0, 5.0), 
   (:Al, :Al) => (2.0, 5.0), 
   (:C, :C) => (1.5, 5.2), 
   (:Al, :Fe) => (1.5, 5.0) 
 )

trans = multitransform(transforms, cutoffs)
```

**Comment by gabor1** [comment]
Why the “+1”?

— Gábor

Gabor Csanyi
Professor of Molecular Modelling
Engineering Laboratory
University of Cambridge

**Comment by cortner** [comment]
just to test some random transformation parameters. I'm only asking whether this is ok as a mechanism to supply different cutoffs for different species.

**Comment by davkovacs** [comment]
This interface looks very neat to me.

**Comment by cortner** [comment]
please see updates PR

**Comment by cortner** [comment]
will close this since it is now all working in PR #79 ; we have all discussion there now, but can of course re-open if needed.
