### ISSUE TITLE
Constant term in ACE basis

### ISSUE THREAD

**Issue by zhanglw0521** [ACEsuit/ACE.jl#80]
Adding a constant term ($c\in\mathbb{C}$ for invariant basis and $$cI(2L+1)$$ for `SphericalMatrix(L,L) `) to the corresponding ACE basis would not destroy the symmetry of the basis and may help improve the fitting result as well as stability (Maybe?). 

We could add it directly to the basis while another thought could be that we add a `mean` field for ACELinearModels, which contains the mean value of data. This means that we didn't fit the coefficient for the constant term but give an expected value to it.

**Comment by cortner** [comment]
This has been merged and is tagged as v0.12.24
