### ISSUE TITLE
quickstart not working

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACE.jl#82]
Cleaned up my julia installation so I can use a binary that works on all my nodes, and when I took the opportunity to clean up everything and start over, the instructions in the quickstart https://github.com/ACEsuit/ACE.jl/tree/dev-v0.8.x#quickstart don't work.  Linux, stock julia 1.7 binary download, and I get
```
(@v1.7) pkg> registry add https://github.com/JuliaMolSim/MolSim.git 
     Cloning registry from "https://github.com/JuliaMolSim/MolSim.git"
       Added registry `MolSim` to `~/.julia/registries/MolSim`

(@v1.7) pkg> add JuLIP, ACE, IPFitting
    Updating registry at `~/.julia/registries/MolSim`
    Updating git-repo `https://github.com/JuliaMolSim/MolSim.git`
   Resolving package versions...
ERROR: cannot find name corresponding to UUID 49dc2e85-a5d0-5ad3-a950-438e2897f1b9 in a registry

(@v1.7) pkg> add JuLIP, ACE
   Resolving package versions...
ERROR: cannot find name corresponding to UUID 49dc2e85-a5d0-5ad3-a950-438e2897f1b9 in a registry
```

**Comment by casv2** [comment]
Very strange as it seems all of these in here...? https://github.com/JuliaMolSim/MolSim

**Comment by bernstei** [comment]
This suggests I have to add the general registry first https://forum.mimiframework.org/t/error-installing-mimi-under-v1-3-1/109/3

**Comment by cortner** [comment]
The general registry really should be installed automatically. Maybe this is a recent change in Julia. Definitely need to look into this. (The point is that all the packages that the MolSim packages depend on are registered in General)

**Comment by cortner** [comment]
closing this in view of the ACE1 activity.
