### ISSUE TITLE
Custom distance transform

### ISSUE THREAD

**Issue by davkovacs** [ACEsuit/ACE.jl#83]
It would be nice to have the option for implementing custom distance transforms based on simple formulae.

**Comment by davkovacs** [comment]
(This is for the dev-v0.8.x branch)

**Comment by cortner** [comment]
this is now part of PR #79 . Please test it. At the moment I'm asking you to define the inverse analytically. But we can discuss providing that numerically as well.

**Comment by cortner** [comment]
Usage:
```julia
trans = ACE.Transforms.AnalyticTransform(
            "r -> exp(- 1.234 * r^2)", "x -> sqrt(- log(x) / 1.234)")
```

**Comment by cortner** [comment]
closing this now, please re-open if you need anything else here.
