### ISSUE TITLE
Development branches of ACE don't support current version of JuLIP

### ISSUE THREAD

**Issue by WillBaldwin0** [ACEsuit/ACE.jl#91]
When I locally modified the Project.toml file in ACE dev-v0.8.x, so that I could update JuLIP to JuLIP 0.13, I found that databases would no longer build, so there is a conflict somewhere between ACE, IPFitting and JuLIP 0.13.

**Comment by cortner** [comment]
There is likely a reason I put a version bound. Can you please remind me why you want to use later JuLIP versions?

**Comment by WillBaldwin0** [comment]
I was planning to use some JuLIP functions which write .xyz files directly from julia, which only appeared in recently in JuLIP.

**Comment by cortner** [comment]
I've back ported the ExtXYZ-JuLIP connection to JuLIP v0.11.3 and now allow ACE v0.8.10 to use JuLIP v0.11.3. I've done limited tests, but they seem to be ok. 

So please update your version bounds to ACE 0.8.10, and check that this automatically updates JuLIP to 0.11.3. Let me know if there are any issues (re-open this.)
